SSSD/sssd-test-framework

- sssd_test_framework/config.py
- sssd_test_framework/hosts/base.py
- sssd_test_framework/hosts/client.py
- sssd_test_framework/roles/client.py
- sssd_test_framework/utils/sssd.py
Avoid repeating operations that can be done only once:
- systemd override
- backup
> sssd: improve setup performance

- sssd_test_framework/roles/samba.py
--nis-domain is required if group is created with POSIX gid, otherwise
we get:
```
Command #9 exited with return code 255:
Command:
samba-tool group add tgroup --gid-number 20001 --group-scope Global --group-type Security
Error output:
ERROR: Both --gid-number and --nis-domain have to be set for a RFC2307-enabled group. Operation cancelled.
```
The value is just stored in msSFU30NisDomain attribute of the group
which is not used by SSSD and does not have any meaning to use or samba.
Therefore we can just hard code the value instead of making it
configurable.
> samba: add nis-domain if gid is added to group

- sssd_test_framework/utils/authentication.py
Some actions may be quite slow (like waiting for SSSD timeouts to
go offline), let's increase the timeout. If this does not help in
long run, we should make the timeout configurable and set required
value in specific test cases.
> authentication: increase authentication timeout

- docs/guides/check-sssd-functionality.rst
- sssd_test_framework/markers.py
The marker can now tests features on any role and on multiple roles
at once.
This will be usefull for testing passkey feature, e.g.
@pytest.mark.builtwith(client="passkey", ipa="passkey")
---
Requires: https://github.com/next-actions/pytest-mh/pull/15
> markers: make builtwith generic

- sssd_test_framework/hosts/client.py
- sssd_test_framework/hosts/ipa.py
This allows to skip passkey tests when the functionality isn't provided.
Requires: https://github.com/next-actions/pytest-mh/pull/15 and https://github.com/SSSD/sssd-test-framework/pull/42 to work.
I have created a new branch, [ikerexxe/testmarker2](https://github.com/ikerexxe/sssd-test-framework/tree/testmarker2), that contains all the changes necessary from this project to test.
In the sssd project, where your test lies, edit the `requirements.txt` file to point to the revision that we'd like to test:
```
pytest
git+https://github.com/next-actions/pytest-importance
git+https://github.com/pbrezina/pytest-mh/@require
git+https://github.com/next-actions/pytest-ticket
git+https://github.com/next-actions/pytest-tier
git+https://github.com/next-actions/pytest-output …
```
> hosts: add passkey feature detection in client and IPA

- docs/guides/using-roles.rst
- sssd_test_framework/utils/sssd.py
'config_file_version' option is obsolete / optional for a long time already, its usage doesn't make any sense.
Moreover, I plan to remove it from SSSD code base in https://github.com/SSSD/sssd/pull/6924
> Remove references to obsolete 'config_file_version' sssd.conf option

- sssd_test_framework/utils/sssd.py
Create a module that will configure nslcd in client machine.
> Add a module for nsldc support.

- sssd_test_framework/utils/authentication.py
Hi,
I edited password change method that it takes additional argument `retyped`. It is needed when the test needs to fail due to mismatched passwords. I also made a cleanup of this method (docstring value `raises`, exit codes now make better sense, assert on line 994 removed)
If you have any comments or suggestions do not hesitate to write.
> authentication: password change take retyped argument

- sssd_test_framework/misc/__init__.py
- tests/test_misc.py
When LDAP attributes values are too long, they split into multiple lines. It can look like the example provided, where ``originalDN`` is the problematic attribute:
```
dn: name=ae3c2c8c-4b8f-11ee-ac71-c6e1a1a33042,cn=hbac_rules,cn=custom,cn=test,cn=sysdb
originalDN: ipaUniqueID=ae3c2c8c-4b8f-11ee-ac71-c6e1a1a33042,cn=hbac,dc=ipa,dc
=test
serviceCategory: all
```
And this caused an error in ``attrs_parse()`` function. I added two tests to check this error, so look there for better understanding of the problem.
This is not a very nice solution, but I couldn't think of a better one. Feel free to suggest changes.
> MISC: attrs_parse() fixed error when multi-line value appeared

- requirements.txt
- sssd_test_framework/utils/authentication.py
The issue is an infinite loop in cares.
generate_unique_id() caused by 'LD_PRELOAD=/opt/random.so'.
generate_unique_id() is calling arc4random_buf() and the loop in cares
is keeping a list of old ids to avoid those. But arc4random_buf() is
overwritten by random.so and always returns the same value and as a
result the same id is always used and causes the infinite loop.
To make the environment only available to
passkey_child not to add those environment variable to
/etc/sysconfig/sssd but rename passkey_child.
Signed-off-by: Madhuri Upadhye <mupadhye@redhat.com>
> passkey: avoid an infinite loop in cares in authentication of passkey

- sssd_test_framework/roles/ldap.py
When calling `passkey_add()` append the new passkey mapping data.
> roles: add `passkeyUser` objectClass only once

- sssd_test_framework/hosts/ad.py
Currently, there is an error in the command output.
> ad: avoid error if backup file does not exist

- sssd_test_framework/roles/ipa.py
Recent changes to attrs_parse broke ipa.get since the output of ipa
*-show command prepends the attributes with single space.
> ipa: fix get methods

- sssd_test_framework/misc/__init__.py
- tests/test_misc.py
AD user get data was being returned with left over white space at the end of the keys.  Changing lstrip to strip in attrs_parse misc function to remove the whitespace at the end of the keys as well as the beginning.
> attrs_parse: strip whitespace from end of key

- requirements.txt
- sssd_test_framework/hosts/client.py
- sssd_test_framework/utils/sssd.py
Sudo tests are failing as a result of KCM not being started. `systemd` refuses to start KCM because some tests are starting and stopping KCM too quickly and `systemd` considers this is a failure.
To avoid this behavior, `pytest-mh` now resets the failed flag every time a unit is started. Because this behavior was changed specifically for this fix, we need to get https://github.com/next-actions/pytest-mh/pull/34 pulled before pulling this one.
in addition, we made the handling of KCM coherent through the `start()`, `stop()`, `restart()` and their asynchronous versions. So far only `start()` would stop KCM for it to re-read its configuration.
Because of the changes in `pytest-mh`, disabling the bust limit is no longer necessary and was removed.
> Solve KCM failure on system tests on F40

- .github/workflows/ci.yml
- tox.ini
This will allow to check the code against both pypi and upstream version
of pytest-mh.
> ci: run also against latest pytest-mh

- sssd_test_framework/hosts/ad.py
- sssd_test_framework/hosts/base.py
- sssd_test_framework/hosts/ipa.py
- sssd_test_framework/hosts/kdc.py
- sssd_test_framework/hosts/samba.py
- sssd_test_framework/roles/ad.py
- sssd_test_framework/roles/kdc.py
- sssd_test_framework/roles/samba.py
- adding a generic domain and realm variable that can be used in tests, as provider.host.domain/realm
- updated existing functions to find the domain to use the new variable instead
> hosts: adding domain and realm variables

- sssd_test_framework/topology.py
Recent patches in pytest-mh did a minor breaking change. This does
not yet affect the tests, but we need to amend our custom topology
mark.
In future, we can use the topology controller to perform complex
topology setup such as setting trust etc.
> topology: prepare for topology controller

- sssd_test_framework/roles/ad.py
- sssd_test_framework/roles/generic.py
- sssd_test_framework/roles/ipa.py
- sssd_test_framework/roles/ldap.py
- sssd_test_framework/roles/samba.py
This is a follow up of https://github.com/SSSD/sssd-test-framework/pull/74
@danlavu  It adds domain and realm to role objects as well as a shortcut.
> roles: add domain and realm to providers

- sssd_test_framework/utils/authentication.py
some test cases will need to check the ssh output
> utils: added password_with_output function to capture ssh output

- sssd_test_framework/hosts/client.py
Using option name makes it less prone to formatting / wording changes.
> CLIENT: fix "non-privileged" feature detection

- sssd_test_framework/roles/client.py
- sssd_test_framework/utils/local_users.py
useradd will create the home directory
usermod can change the home directory in /etc/passwd but it does not
move it
therefore we need to make sure that it is removed (or restored)
correctly
> utils: backup home directory when creating local user

- sssd_test_framework/hosts/ipa.py
IPA got stuck after restoring data in some cases, adding restart to alleviate the issue.
> hosts: add ipa restart after restore

- docs/guides/index.rst
- docs/guides/testing-gpo.rst
- sssd_test_framework/hosts/ad.py
- sssd_test_framework/misc/__init__.py
- sssd_test_framework/roles/ad.py
- sssd_test_framework/utils/authentication.py
- tests/test_misc.py
- create gpo class to manage group policy objects; add(), link(), unlink(), permissions(), policy(), remove(), 
- moved attrs_to_hash to the roles class so other classes can inherit it
- updated adobject with get_sid method 
- added specific gpo backup and restore methods
- updated authentication expect catch for users not in a policy
- create ad computer class to move the computer object
- increased default authentication timeout in utils.authentication.py
> roles: adding gpo functions to AD role

- .github/workflows/ci.yml
- pyproject.toml
- requirements.txt
- sssd_test_framework/config.py
- sssd_test_framework/hosts/ad.py
- sssd_test_framework/hosts/base.py
- sssd_test_framework/hosts/client.py
- sssd_test_framework/hosts/ipa.py
- sssd_test_framework/hosts/kdc.py
- sssd_test_framework/hosts/keycloak.py
- sssd_test_framework/hosts/ldap.py
- sssd_test_framework/hosts/nfs.py
- sssd_test_framework/hosts/samba.py
- sssd_test_framework/misc/__init__.py
- sssd_test_framework/misc/ssh.py
- sssd_test_framework/roles/base.py
- sssd_test_framework/roles/ipa.py
- sssd_test_framework/topology.py
- sssd_test_framework/topology_controllers.py
- sssd_test_framework/utils/pam.py
- sssd_test_framework/utils/sshd.py
- sssd_test_framework/utils/sssd.py
- tests/test_misc.py
- tox.ini
Currently, we provide machines that are already fully setup with the
client enrolled into all domains and trusts established. This is no
longer necessary. With this patch, we will enroll into the domains
using per-topology setup if needed.
It adds also provisioned_topologies field to mhc.yaml to avoid
additional provisioning attempt if the topology is already fully setup.
---
Please note that this needs to be closed together with changes to other repositories:
* https://github.com/SSSD/sssd/pull/7349
* https://github.com/SSSD/sssd-ci-containers/pull/95
* https://github.com/next-actions/pytest-mh/pull/54
> topology: provision topologies if not already using per-topology setup

- docs/guides/index.rst
- docs/guides/testing-dbus.rst
- readme.md
- sssd_test_framework/roles/client.py
- sssd_test_framework/utils/dbus/types.py
- sssd_test_framework/utils/sbus.py
Provides a set of objects able to handle D-Bus operations: method invocation, property access and node navigation.
All this is automatically done by using introspection to detect the structure.
The back-end uses dbus-send as it must be executed through ssh.
Some example tests can be seen [here](https://github.com/aplopez/sssd/blob/dbus/src/tests/system/tests/test_infopipe.py). Once this PR approved, a new PR will be opened to merge these tests.
Documentation is part of this PR.
Resolves: https://issues.redhat.com/browse/SSSD-6323
> DBUS: Add support for D-Bus

- sssd_test_framework/misc/__init__.py
- tests/test_misc.py
Powershell returns \r\n for a new line, and \r can be left after processing the ssh result as below. It causes ValueError in attrs_parse.
lines = ['\r', '\r', 'DistinguishedName : CN=Domain Admins,CN=Users,DC=ad-n97b,DC=test\r',...
line       = '\r'
```
>           (key, value) = map(lambda x: x.lstrip(), line.split(":", 1))
E           ValueError: not enough values to unpack (expected 2, got 1)
```
This removes the carriage return char in attrs_parse before checking attr.
> MISC: Remove a carriage return char at each line end if it exists

- docs/config.rst
- requirements.txt
- sssd_test_framework/roles/base.py
This utility can automatically collect audit.log and detect AVC
denials. If AVC denial is detected it can warn or fail the test.
Auditd does not really work on containers, therefore the feature
is disabled by default.
Requires:
* https://github.com/next-actions/pytest-mh/pull/60
* https://github.com/next-actions/pytest-mh/pull/61
> roles: add pytest-mh auditd and coredumpd utility to linux roles

- docs/guides/index.rst
- docs/guides/skipping-conditional-tests.rst
- docs/guides/testing-authentication.rst
- docs/guides/testing-autofs.rst
- docs/guides/testing-dbus.rst
- docs/guides/testing-gpo.rst
- docs/guides/testing-identity.rst
- docs/guides/testing-ipa-trust.rst
- docs/guides/testing-ldap-krb5.rst
- docs/guides/testing-local-overrides.rst
- docs/guides/testing-local-users.rst
- docs/guides/testing-netgroups.rst
- docs/guides/testing-offline.rst
- docs/guides/testing-pam.rst
- docs/guides/testing-passkey.rst
- docs/guides/using-roles.rst
- docs/guides/using-ssh.rst
* the naming was a little inconsistent and looked strange, generalized some of the titles and files.
> docs: refactoring guide titles and files

- sssd_test_framework/hosts/client.py
- sssd_test_framework/utils/sssd.py
Usage example: https://github.com/SSSD/sssd/pull/7513
> SSSD: use systemd service description to configure service user

- requirements.txt
- sssd_test_framework/config.py
- sssd_test_framework/hosts/base.py
- sssd_test_framework/hosts/client.py
- sssd_test_framework/hosts/nfs.py
- sssd_test_framework/topology_controllers.py
While rewriting pytest-mh documentation I realized that some methods
are marked with underscore to make them private, however, these methods
are actually expected to be overwritten. Therefore they should be public.
* https://github.com/next-actions/pytest-mh/pull/81
* https://github.com/next-actions/pytest-mh/pull/82
Additionally, I also make our backup code generic and pushed it into pytest-mh. This is not a breaking change, but it starts using this generic code instead of our own implementation.
* https://github.com/next-actions/pytest-mh/pull/79
> Make code compatible with latest pytest-mh changes

- sssd_test_framework/utils/sssd.py
Otherwise using percent sign will raise an error, e.g.:
```
client.sssd.domain["override_homedir"] = "/home/%u"
```
```
self = <configparser.BasicInterpolation object at 0x7fe0fcb46810>
parser = <configparser.ConfigParser object at 0x7fe0fca92fd0>
section = 'domain/test', option = 'override_homedir', value = '/home/%u'
def before_set(self, parser, section, option, value):
tmp_value = value.replace('%%', '') # escaped percent signs
tmp_value = self._KEYCRE.sub('', tmp_value) # valid syntax
if '%' in tmp_value:
>           raise ValueError("invalid interpolation syntax in %r at "
"position %d" % (value, tmp_value.find('%')))
E           ValueError: invalid interpolation syntax in '/home/%u' at position 6
/usr/lib64/python3.11/configparser.py:403: ValueError
```
> sssd: disable interpolation for configparser

- sssd_test_framework/hosts/ipa.py
- sssd_test_framework/misc/ssh.py
ipa-restore sometimes returns 0 but does not restore IPA correctly.
```
+ ipa-restore --unattended --password Secret123 --data --online /tmp/tmp.aBMkEEeqbD/ipa
Preparing restore from /tmp/tmp.aBMkEEeqbD/ipa on master.ipa.test
Performing DATA restore from DATA backup
Temporary setting umask to 022
Each master will individually need to be re-initialized or
re-created from this one. The replication agreements on
masters running IPA 3.1 or earlier will need to be manually
re-enabled. See the man page for details.
Disabling all replication.
Starting Directory Server
Restoring from userRoot in IPA-TEST
Unable to bind to LDAP server: Operations error:
Restoring from ipaca in IPA-TEST
Waiting for LDIF to finish
Restoring umask to 18
The ipa-restore command was successful
```
> ipa: retry restore if it fails to bind to LDAP

- sssd_test_framework/hosts/base.py
We need distro information in order to match expected features to distros and versions.
> hosts: Add distro information to BaseLinuxHost

- sssd_test_framework/hosts/samba.py
- sssd_test_framework/roles/ad.py
- sssd_test_framework/roles/generic.py
- sssd_test_framework/roles/samba.py
* added SambaSite object
* added SambaComputer object
* added GenericGPO class and methods
* added some ldap variables to perform ldap functions
> roles: adding gpo management to samba role

- sssd_test_framework/roles/ad.py
- sssd_test_framework/roles/samba.py
Otherwise we use the ssh/ldap connection inside the constructor
which can cause troubles.
> roles: make naming_context a @property

- sssd_test_framework/hosts/base.py
Find package version and parse it to major, minor, patch, release.
This is needed to detect sssd and ipa-client version to match  expected features against versions and put workaround for RHEL 10 gating.
> feat: Implement get_package_version in hosts/base.py

- sssd_test_framework/hosts/ipa.py
kinit was run every time this property was accessed. This caused
"Calling exit but enter was not called" exception in pytest-mh
under special conditions:
- a test fails in a way that leaves IPA inoperable
- IPA restore does not work
- new test has `builtwith` marker that access IPA.features
In this case kinit was called, failed and exepction was thrown.
pytest-mh then skipped setup but attempted to teardown
> ipa: do not attempt to kinit if features are already detected

- sssd_test_framework/hosts/base.py
- sssd_test_framework/hosts/client.py
- sssd_test_framework/utils/tools.py
While implementing shadow's test framework I discovered several issues that I've fixed
> Minor fixes

- sssd_test_framework/hosts/base.py
This docstring produced sphinx warning:
```
/home/runner/work/sssd-test-framework/sssd-test-framework/sssd_test_framework/hosts/base.py:docstring of sssd_test_framework.hosts.base.BaseLinuxHost.get_package_version:3: WARNING: Definition list ends without a blank line; unexpected unindent. [docutils]
```
> hosts: fix docstring

- sssd_test_framework/hosts/client.py
- sssd_test_framework/utils/sssd.py
Two commits:
1. Adding a clean parameter to mkhomedir common configuration, the override_homedirs are failing because some directories already exist from other tests.  After backing up homedir path, it will not clear it as well. 
2. Adding a clean parameter to sssd start, restart to condense 
```
client.sssd.stop()
client.sssd.clear()
client.sssd.start()
```
to 
```
client.sssd.restart(clean=True)
```
> utils sssd, adding clean flag, clearing the cache on starts and restarts

- sssd_test_framework/utils/authentication.py
Some tests will require to connect using the client hostname instead of localhost, adding this flexibility.
> authentication: adding hostname parameter to ssh method

- sssd_test_framework/hosts/client.py
The /home is mountpoint so deleting it on real machine for backup and restore does not work in idmci.
> hosts: client, do not delete /home during restore

- sssd_test_framework/utils/tools.py
Create method to find currently connected network interface
> Create method to find currently connected network interface

- sssd_test_framework/roles/generic.py
- sssd_test_framework/roles/ipa.py
- sssd_test_framework/roles/ldap.py
- Adding email attribute to GenericUser;
- Keeping mail and email (retro-compatibility) for LDAP tests while we standardize it. I'll open a new PR to remove the mail and keep it there to be merged after we deal with sssd tests.
> Add email attribute to GenericUser

- docs/running-tests.rst
While installing libvirt for the first time on a new system, I was unable to connect to the libvirt daemon.  I had to grant libvirt/qemu user permissions.
> Docs lib virt user permissions

- sssd_test_framework/misc/__init__.py
- sssd_test_framework/roles/ad.py
- sssd_test_framework/roles/generic.py
- sssd_test_framework/roles/ipa.py
- sssd_test_framework/roles/ldap.py
- sssd_test_framework/roles/samba.py
- sssd_test_framework/utils/authentication.py
- tests/test_misc.py
Tests PR, https://github.com/SSSD/sssd/pull/7728
This PR is larger than I expected. 
**misc.py**
* added seconds to timespan method and test, timespan is the powershell M:D:H:S:F format 
**authentication.py**
* SUAuthentication, added password_expired_with_output
* SSHAuthentication, added password_expired_with_output
* like password_with_out, replaced put with a valid {{exitmsg}}
**roles/ad.py, roles/ipa.py, roles/samba.py, roles/ldap.py**
* added PasswordPolicy class
* password.lockout(duration, attempts)
* password.complexity(enable)
* additionally to LDAP, added  password.get() and password.set() and added ACI to the password constructor. 
**roles/generic.py**
* added GenericPasswordPolicy class
> roles, adding default domain password policy management 

- sssd_test_framework/roles/ipa.py
Add sub classes for IPA ID override for users
and groups.
> IPA ID Override classes for users and groups

- sssd_test_framework/hosts/ipa.py
```
6f42391 (Pavel Březina, 24 hours ago)
ipa: truncate logs before each test
So we can collect fresh logs from each test run. We use truncate insted of
rm to avoid additional and time consuming IPA service restart.
0635309 (Pavel Březina, 24 hours ago)
ipa: print backup and restore logs on failure
These commands fail from time to time, it may be good to have more 
information then the output.
353c783 (Pavel Březina, 24 hours ago)
ipa: perform offline backup and restore
It does not seem to have any performance impact anymore and may be more
reliable then online backup and restore.
```
> ipa: improvements to IPA artifacts

- sssd_test_framework/hosts/ad.py
- sssd_test_framework/hosts/ipa.py
- sssd_test_framework/hosts/samba.py
- sssd_test_framework/roles/samba.py
Declaring an administrative user across ad, ipa, samba hosts. This uniform declaration will help to use admin user intuitively in tests
> Uniform admin user declaration

- sssd_test_framework/utils/adcli.py
Adding methods for presetting, and reseting the computer accounts on AD. The preset operation will pre-creates one or more computer accounts in the domain for machines to later use when joining the domain, whereas 'adcli reset' operation resets the computer account
> Adcli preset, reset method

- sssd_test_framework/hosts/ipa.py
the missing symlink is causing ipa-backup to fail.
> creating symlink for dsctl binary

- sssd_test_framework/hosts/ipa.py
Reverts SSSD/sssd-test-framework#196
This was a temporary fix.
> Revert "creating symlink for dsctl binary"

- .github/workflows/ci.yml
Running only against one distribution is enough, since we are not
testing SSSD, just the framework.
> ci: run SSSD tests to avoid breaking it
