SSSD/sssd-test-framework

- docs/guides/index.rst
- docs/guides/testing-netgroups.rst
- sssd_test_framework/roles/ad.py
- sssd_test_framework/roles/generic.py
- sssd_test_framework/roles/ipa.py
- sssd_test_framework/roles/ldap.py
- sssd_test_framework/roles/samba.py
- sssd_test_framework/utils/tools.py
This PR also contains to fixes for the get method.
> Add API for testing netgroups

- docs/guides/testing-identity.rst
- sssd_test_framework/utils/tools.py
Tool for calling `getent initgroups $name`. Needed for memory_cache tests.
I look forward for your comments.
> tools: getent initgroups added

- docs/guides/index.rst
- docs/guides/sss_override.rst
- sssd_test_framework/roles/client.py
- sssd_test_framework/utils/sss_override.py
- OverrideUtils Object, user and group sub classes
- OverrideUser Object adding override.user add, delete, get, modify, backup and restore functions
- OverrideGroup Object adding override.group add, delete, get, modify, backup and restore functions
> sss_override: add utility to manage local overrides

- sssd_test_framework/utils/sssctl.py
Adding `sssctl user-checks name` to framework.
> sssctl: user-checks added

- sssd_test_framework/utils/sssctl.py
Command `sssctl config-check` added
> sssctl: config_check command added

- sssd_test_framework/roles/kdc.py
If I'm not mistaken there was a typo.
> kdc: trivial typo

- sssd_test_framework/utils/authentication.py
Functionality for password change.
Looking forward to feedback :+1:
> authentication: add PasswdUtils

- sssd_test_framework/utils/sssctl.py
I added function to call ``sssctl user-show`` with additional arguments.
Waiting for your comments
> sssctl: user-show command added

- sssd_test_framework/hosts/ldap.py
- sssd_test_framework/markers.py
A feature may have dependencies in several hosts, so we need to check
for it in all of them. Adding topology information to the feature
detection mechanism.
If client detection is present it always needs to be checked, other
hosts will be skipped if they aren't present in the topology.
Moreover, add passkey feature detection in ldap.
Depends on https://github.com/next-actions/pytest-mh/pull/18
> Add topology to feature detection

- sssd_test_framework/utils/tools.py
Function for waiting for bash commands. If something is not clear, please suggest changes.
> Tools: wait_for() added

- sssd_test_framework/utils/sssctl.py
Ask, if something is not clear.
> sssctl: sssctl analyze command added

- sssd_test_framework/roles/base.py
Depends on https://github.com/SSSD/sssd-ci-containers/pull/62 and https://github.com/next-actions/pytest-mh/pull/22
> Roles: import utility to perform traffic control

- docs/guides/using-roles.rst
- sssd_test_framework/config.py
- sssd_test_framework/hosts/keycloak.py
- sssd_test_framework/roles/ad.py
- sssd_test_framework/roles/keycloak.py
Adding role and topology for Keycloak to support new tests that require Keycloak IdP.
> Add Keycloak role and topology

- sssd_test_framework/utils/authentication.py
The passwd binary from shadow utils has slightly different outputs.
> utils: passwd from shadow utils

- sssd_test_framework/roles/client.py
- sssd_test_framework/roles/ipa.py
This will allow us to test sss_ssh_knownhosts command from https://github.com/SSSD/sssd/pull/7144.
The following change to sssd-ci-containers is required as well:
https://github.com/SSSD/sssd-ci-containers/pull/76
> Add IPAHostAccount and sss_ssh_knownhosts

- sssd_test_framework/hosts/ipa.py
- sssd_test_framework/hosts/ldap.py
Check if the ldap is running and try to start it when needed.
Start ipa when needed.
> hosts: Make sure ldap and ipa are running for each test

- sssd_test_framework/roles/ipa.py
Add attribute to add supported user authentication for IPA user.
> ipa: add user_auth_type attribute

- sssd_test_framework/utils/authentication.py
Update the passkey authentication method to run command after authentication of user
and get the expected output of that command.
> authentication: Update passkey auth to run the command after auth of the user

- sssd_test_framework/roles/ipa.py
Add a string attribute to user_auth_type
> ipa: Add the str to user_auth_type

- sssd_test_framework/hosts/client.py
Detect ldap_use_ppolicy and sss_ssh_knownhostsproxy features.
> hosts: Add Additional feature detection to client.

- sssd_test_framework/hosts/client.py
This does not work as pytest-mh using the ansible ssh lib does not request terminal:
man sssd.conf | grep -q "id_provider = ldap or id_provider = proxy" && echo "limited_enumeration" || :
> hosts: Update feature detection on client

- sssd_test_framework/utils/sssd.py
In image mode the sevice file is not editable so we skip tests that are not applicable.
> utils: set_service_user skip on read only filesystem

- sssd_test_framework/utils/tools.py
* renamed the path variable to homedir, matching other functions
* added comment to the keys making it easier to distinguish keys during debugging
> tools.py - ssh-keygen

- docs/running-tests.rst
Documentation: update adding libssh and libssh-devel as dependencies
> docs: add dependencies for pylibssh

- sssd_test_framework/topology.py
DS, any server that contains ldap, kerberos and a ca by default. This group will contain AD, Samba and IPA. Dynamic DNS, PKI tests will use this TopologiesGroup.
> topologies: adding any directory server (ds)

- sssd_test_framework/roles/client.py
- sssd_test_framework/utils/realmd.py
realm utility is a tool manage enrollment in realm. This PR is adding methods provided by realm utility.
> realm: add methods for realm utility

- sssd_test_framework/utils/sbus.py
Skip output parsing when self.output is empty, which happens for void methods like UpdateMemberList. Return None instead of attempting to access values[0].
> fix(sbus): prevent IndexError in methods with no output args

- sssd_test_framework/roles/client.py
- sssd_test_framework/utils/adcli.py
Adding adcli class, and methods including info, discovery, join
> Adcli: Adding adcli class

- sssd_test_framework/utils/tools.py
```
sssd_test_framework/utils/tools.py:204: error: Argument "name" to "PasswdEntry" has incompatible type "str | int | None"; expected "str"  [arg-type]
sssd_test_framework/utils/tools.py:205: error: Argument "password" to "PasswdEntry" has incompatible type "str | int | None"; expected "str"  [arg-type]
sssd_test_framework/utils/tools.py:206: error: Argument "uid" to "PasswdEntry" has incompatible type "str | int | None"; expected "int"  [arg-type]
sssd_test_framework/utils/tools.py:207: error: Argument "gid" to "PasswdEntry" has incompatible type "str | int | None"; expected "int"  [arg-type]
sssd_test_framework/utils/tools.py:208: error: Argument "gecos" to "PasswdEntry" has incompatible type "str | int | None"; expected "str"  [arg-type]
sssd_test_framework/utils/tools.py:209: error: …
```
> tools: fix types to satisfy mypy

- sssd_test_framework/misc/__init__.py
- sssd_test_framework/roles/base.py
- sssd_test_framework/utils/network.py
- sssd_test_framework/utils/tools.py
adding basic ip utilties such as getting the default gateway, ip, netmask, nameserver and creating a dummy interface.
> adding IPUtils interface

- sssd_test_framework/misc/__init__.py
- tests/test_misc.py
new utility function get_attr in misc/common.py that simplifies working with raw IPA command output in test cases.
Key Changes:
Added get_attr(raw, key, default) helper:
Case-insensitive attribute lookup
Flattens single-element lists
Converts "TRUE"/"FALSE" → bool
Converts digit strings → int
Keeps multi-value lists intact
before:
```
raw_result = ipa.user("user-1").iduseroverride().show_override("testview1")
assert certificate_content in raw_result.get("usercertificate", [""])[0]
```
after:
```
from sssd_test_framework.misc.common import get_attr
raw_result = ipa.user("user-1").iduseroverride().show_override("testview1")
assert certificate_content in get_attr(raw_result, "usercertificate")
assert get_attr(result, "enabled") is True
assert get_attr(result, "uid") == 1001
assert "ssh" in …
```
> feat(misc): add get_attr helper for normalized IPA attributes

- sssd_test_framework/utils/sssd.py
* set_server
* set_invalid_primary_server
> splitting set_server method into two methods.
